apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespace.yaml
  - ../../base/service-accounts.yaml
  - ../../base/configmap.yaml
  - ../../base/secrets.yaml
  - ../../base/postgres.yaml
  - ../../base/redis.yaml
  - ../../base/api-deployment.yaml
  - ../../base/collaboration-deployment.yaml
  - ../../base/execution-deployment.yaml
  - ../../base/web-deployment.yaml
  - nodeport-services.yaml
