apiVersion: v1
kind: Service
metadata:
  name: codepad-api-nodeport
  namespace: codepad
spec:
  type: NodePort
  selector:
    app: codepad-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: codepad-web-nodeport
  namespace: codepad
spec:
  type: NodePort
  selector:
    app: codepad-web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: codepad-collaboration-nodeport
  namespace: codepad
spec:
  type: NodePort
  selector:
    app: codepad-collaboration
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
      protocol: TCP
