apiVersion: v1
kind: ConfigMap
metadata:
  name: codepad-config
  namespace: codepad
data:
  NODE_ENV: "production"
  API_PORT: "8080"
  CORS_ORIGINS: "http://localhost:30000"
  FRONTEND_URL: "http://localhost:30000"
  API_URL: "http://codepad-api:8080"
  REDIS_URL: "redis://redis:6379"
  EXECUTION_ENGINE_URL: "http://codepad-execution:8081"
  WS_PORT: "8082"
  LOG_LEVEL: "info"
