apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api-deployment.yaml
  - collaboration-deployment.yaml
  - execution-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml
  - monitoring.yaml
  - network-policies.yaml
  - postgres.yaml
  - redis.yaml
  - service-accounts.yaml
