apiVersion: v1
kind: ServiceAccount
metadata:
  name: codepad-api
  namespace: codepad
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codepad-collaboration
  namespace: codepad
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codepad-execution
  namespace: codepad
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codepad-web
  namespace: codepad

